# Generated by Django 5.2.4 on 2025-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='industries',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobrecords', to='jobrecord.industry'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobrecords', to='jobrecord.skill'),
        ),
    ]
